# Generated by Django 4.2.23 on 2026-02-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_batch_course'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.CharField(max_length=9, null=True)),
                ('semester', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'examinations',
            },
        ),
        migrations.CreateModel(
            name='FacultyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'faculty_course',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.CharField(max_length=20)),
                ('registration_type', models.CharField(default='regular', help_text='Type of registration (e.g., regular, supply, improvement)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'student_course',
            },
        ),
        migrations.RemoveField(
            model_name='facultysubject',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='facultysubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='subject',
        ),
        migrations.RemoveConstraint(
            model_name='exam',
            name='chk_exam_sem_1_8',
        ),
        migrations.RemoveConstraint(
            model_name='examslot',
            name='uq_exam_slot_time',
        ),
        migrations.RemoveConstraint(
            model_name='studentacademicdata',
            name='chk_sad_sem_1_8',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='exam_academi_63b6b5_idx',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='examslot',
            name='exam_name',
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='masters.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='regulation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examslot',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='examslot',
            name='exam_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='examslot',
            name='mode',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='examslot',
            name='slot_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentacademicdata',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='examslot',
            constraint=models.UniqueConstraint(fields=('exam_date', 'start_time', 'end_time', 'slot_code', 'exam_type', 'mode'), name='uq_exam_slot_time'),
        ),
        migrations.DeleteModel(
            name='FacultySubject',
        ),
        migrations.DeleteModel(
            name='StudentSubject',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_map', to='masters.course'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_map', to='masters.student'),
        ),
        migrations.AddField(
            model_name='facultycourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_map', to='masters.course'),
        ),
        migrations.AddField(
            model_name='facultycourse',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_map', to='masters.faculty'),
        ),
        migrations.AddConstraint(
            model_name='examinations',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='start_date_before_end_date'),
        ),
        migrations.AddField(
            model_name='examslot',
            name='examination',
            field=models.ForeignKey(blank=True, db_column='examination_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.examinations'),
        ),
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['academic_year'], name='student_cou_academi_8fb926_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['semester'], name='student_cou_semeste_c89eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['course'], name='student_cou_course__099850_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['student'], name='student_cou_student_1b5cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['student', 'academic_year', 'semester'], name='student_cou_student_eaea11_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentcourse',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'academic_year', 'semester'), name='uq_student_course'),
        ),
        migrations.AddConstraint(
            model_name='facultycourse',
            constraint=models.UniqueConstraint(fields=('faculty', 'course', 'academic_year', 'semester'), name='uq_faculty_course'),
        ),
    ]
