# Generated by Django 4.2.23 on 2026-02-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_examinations_facultycourse_studentcourse_and_more'),
        ('operations', '0002_update_exam_slot_constraint'),
    ]

    operations = [
    ]
