# Generated by Django 4.2.23 on 2026-02-24 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_merge_20260223_1534'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomallocation',
            name='uq_exam_room',
        ),
        migrations.RemoveField(
            model_name='roomallocation',
            name='exam',
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='exam_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='operations.examslot'),
        ),
        migrations.AddConstraint(
            model_name='roomallocation',
            constraint=models.UniqueConstraint(fields=('exam_slot', 'room'), name='uq_exam_slot_room'),
        ),
    ]
