# Generated by Django 4.2.23 on 2026-03-03 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_roomallocation_uq_exam_room_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomallocation',
            name='uq_exam_slot_room',
        ),
        migrations.RemoveField(
            model_name='roomallocation',
            name='exam_slot',
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='operations.exam'),
        ),
        migrations.AddConstraint(
            model_name='roomallocation',
            constraint=models.UniqueConstraint(fields=('exam', 'room'), name='uq_exam_room'),
        ),
    ]
