# Generated by Django 4.2.23 on 2026-03-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_remove_roomallocation_uq_exam_slot_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomallocation',
            name='exam_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='operations.examslot'),
        ),
    ]
