# Generated by Django 4.2.23 on 2026-03-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_roomallocation_exam_slot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roomallocation',
            name='uq_exam_room',
        ),
        migrations.RemoveField(
            model_name='roomallocation',
            name='exam',
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='examination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='operations.examinations'),
        ),
        migrations.AddConstraint(
            model_name='roomallocation',
            constraint=models.UniqueConstraint(fields=('exam_slot', 'room'), name='uq_exam_slot_room'),
        ),
    ]
