# Generated by Django 4.2.23 on 2026-03-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_facultyavailability_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['academic_year'], name='student_cou_academi_8fb926_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourse',
            index=models.Index(fields=['semester'], name='student_cou_semeste_c89eaa_idx'),
        ),
    ]
