# Generated by Django 4.2.23 on 2026-03-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_studentcourse_student_cou_academi_8fb926_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinations',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
