# Generated by Django 4.2.23 on 2026-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_examinations_published'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examslot',
            name='uq_exam_slot_time',
        ),
        migrations.AddConstraint(
            model_name='examslot',
            constraint=models.UniqueConstraint(fields=('examination', 'exam_date', 'start_time', 'end_time', 'slot_code'), name='uq_exam_slot_time'),
        ),
    ]
