# Generated by Django 4.2.23 on 2026-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_remove_examslot_uq_exam_slot_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='examslot',
            name='uq_exam_slot_time',
        ),
        migrations.AddField(
            model_name='roomallocation',
            name='allocated_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='examslot',
            constraint=models.UniqueConstraint(fields=('exam_date', 'start_time', 'end_time', 'slot_code'), name='uq_exam_slot_time'),
        ),
    ]
