# Generated by Django 4.2.23 on 2026-04-04 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_delete_subject_remove_faculty_email_room_room_type_and_more'),
        ('operations', '0013_remove_examslot_uq_exam_slot_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invigilationduty',
            name='uq_room_once_per_slot',
        ),
        migrations.RemoveField(
            model_name='roomallocation',
            name='allocated_capacity',
        ),
        migrations.AddField(
            model_name='attendance',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.room'),
        ),
    ]
