# Generated by Django 4.2.23 on 2026-04-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_chatmessage_is_deleted_by_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examslot',
            name='registration_type',
            field=models.CharField(default='REGULAR', max_length=20),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
