# Generated by Django 4.2.23 on 2026-04-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_examslot_registration_type_delete_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_step', models.BooleanField(default=False)),
                ('rooms_step', models.BooleanField(default=False)),
                ('faculty_step', models.BooleanField(default=False)),
                ('seating_step', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='operations.examslot')),
            ],
            options={
                'db_table': 'slot_workflow',
            },
        ),
    ]
