# Generated by Django 4.2.23 on 2026-02-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_batch_course'),
        ('operations', '0002_examinations_facultycourse_studentcourse_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='email',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, help_text='Type of room (e.g., Lecture Hall, Lab, etc.)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch/Regulation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='masters.batch'),
        ),
    ]
