# Generated by Django 4.2.23 on 2026-04-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_delete_subject_remove_faculty_email_room_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
